## Logistic Regression

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
class LogisticRegressionGradient():
    def __init__ (self,learning = 0.001,iterations = 5000):
        self.learning = learning
        self.iterations = iterations
    def initialize_weights(self,X):
        #print("Initializing Weights",(X.shape)[1])
        self.weights = np.zeros((X.shape)[1])
    def sigmoid(self,z):
        #print("Entered Sigmoid Function")
        return (1/(1+np.exp(-z)))
    def logLoss(self,X,y):
        #print("LogLoss function is entered!")
        return ((-1/len(y))*(y*np.log(self.sigmoid(np.dot(X,self.weights)))+(1-y)*np.log(1-self.sigmoid(np.dot(X,self.weights)))).sum())
    def gradientDescent(self,X,y):
        return (np.dot(X.T,(y-self.sigmoid(np.dot(X,self.weights)))))
    def fit(self,X,y):
        self.initialize_weights(X)
        for i in range(0,self.iterations):
            self.weights = self.weights + self.learning * self.gradientDescent(X,y)
        print("Finally the weights",self.weights)
    def predict(self,X):
        y_predict = []
        for i in X:
            y_predict.append(self.sigmoid(np.dot(self.weights,i)))
        return y_predict

In [3]:
np.random.seed(1)
number_of_points = 8000
means = [[-1,-1],[0.1,2.8]]
cov = -0.3
covariances = [[[1,cov],[cov,1]],[[1,cov],[cov,1]]] 
a = np.random.multivariate_normal(means[0],covariances[0],number_of_points)
b = np.random.multivariate_normal(means[1],covariances[1],number_of_points)
X = np.array([[0.28,0.98,0.94,0.15],[0.33,0.57,0.58,0.04],[0.23,0.96,0.77,0.97]])
X = np.hstack((np.ones((X.shape[0],1)),X)) # adding column of ones (biases)
y = np.array([1,2,3])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=10)

In [4]:
reg = LogisticRegressionGradient()
reg.fit(X_train,y_train)

Finally the weights [15.16536055  3.99809932 12.5694872  10.70820148  9.96678229]


In [5]:
y_pred = reg.predict(X_test)

In [6]:
for i in range(len(y_pred)):
    if y_pred[i] >= 0.5:
        y_pred[i] = 1
    else:
        y_pred[i] = 0
accuracy_score(y_test,y_pred)

1.0

In [37]:
clf = LogisticRegression()
clf.fit(X_train,y_train)
y_clf = clf.predict(X_test)
accuracy_score(y_test,y_clf)

0.986

# Linear Regression Both Matrix and Gradient Descent Way

## Matrix Way (Suffers when features are dependent)

In [13]:
import numpy as np
from numpy.linalg import inv

In [15]:
X = np.array([[2016],[2017],[2018],[2019],[2020]])
y = np.array([12,19,29,37,45])
X = np.hstack((np.ones((X.shape[0],1)),X))

In [16]:
X

array([[1.000e+00, 2.016e+03],
       [1.000e+00, 2.017e+03],
       [1.000e+00, 2.018e+03],
       [1.000e+00, 2.019e+03],
       [1.000e+00, 2.020e+03]])

In [17]:
inv(np.dot(X.transpose(),X))

array([[ 4.072326e+05, -2.018000e+02],
       [-2.018000e+02,  1.000000e-01]])

In [18]:
y

array([12, 19, 29, 37, 45])

In [19]:
theta = np.dot(np.dot(inv(np.dot(X.transpose(),X)),X.transpose()),y)

In [20]:
theta

array([-1.69228e+04,  8.40000e+00])

In [21]:
np.dot(theta.transpose(),np.array([1,2021]))

53.60000000553919

## Gradient Descent Way

In [8]:
class LinearRegression():
    def __init__ (self,learning = 0.001,iterations = 5000):
        self.learning = learning
        self.iterations = iterations
    def initweights(self,X):
        self.theta = np.zeros(X.shape[1])
    def gradientDescent (self,X,y):
        return X.T.dot(X.dot(self.theta) - y)/(len(y))
    def costFunction(self,X,y):
        m = len(y)
        J = np.sum((X.dot(self.theta)-y)**2)/2/m
        return J
    def fit (self,X,y):
        self.initweights(X)
        for i in range(self.iterations):
            self.theta = self.theta - self.learning*self.gradientDescent(X,y)
        print("Final Theta values",self.theta)
        print("Final cost function",self.costFunction(X,y))
    def predict (self,X):
        return np.dot(self.theta.transpose(),X)

In [9]:
reg = LinearRegression(learning = 0.0001,iterations = 100000)
reg.fit(X,y)

C:\Users\hp\anaconda3\lib\site-packages\ipykernel_launcher.py:16: RuntimeWarning: invalid value encountered in subtract
  app.launch_new_instance()


Final Theta values [nan]
Final cost function nan


In [29]:
reg.predict(np.array([1,3,5]))

16.828517989333076

In [41]:
A =[[1,3],[2,4]]

In [42]:
import numpy as np
Apinv = np.linalg.pinv(A)
print(Apinv)#use this when inverse is not possible
Ainv = np.linalg.inv(A)
print(Ainv)

[[-2.   1.5]
 [ 1.  -0.5]]
[[-2.   1.5]
 [ 1.  -0.5]]


In [43]:
B = [7,10]

In [45]:
A =[[1,3],[2,4]]
B = [7,10]
import numpy as np
Ainv = np.linalg.inv(A)
print(Ainv)
X = np.dot(Ainv,B)
print(X)

[1. 2.]


In [ ]:
A =[[1,3],[2,4]]
B = [7,10]
import numpy as np
Apinv = np.linalg.pinv(A)
print(Apinv)#use this when inverse is not possible
X = np.dot(Apinv,B)#When inverse of A is not possible
print(X)

## Multinomial NB

In [ ]:
class MultinomialNB_own(object):
  def __init__(self,alpha):
    self.alpha = alpha # alpha is just used for smoothening here
  def fit(self,X,y):
    seperated = [[x for x, t in zip(X, y) if t == c] for c in np.unique(y)] # Extracting the rows of each class as a matrix here
    count_sample = (X.shape)[0] # Getting total rows present
    self.class_log_prior_ = [np.log(len(i) / count_sample) for i in seperated] # Calculating the class prior probavilties and applying natural log over it
    count = np.array([np.array(i).sum(axis=0) for i in seperated]) + self.alpha # Counting occurence of each word in each class
    self.feature_log_prob_ = np.log(count / count.sum(axis=1)[np.newaxis].T) # Calculating likelihood probabilities
  def predict_log_proba(self, X):
    return [(self.feature_log_prob_ * x).sum(axis=1) + self.class_log_prior_ for x in X] # Simply caluclating posterior probabilities for each class of the word and returning the array of the values seperated for each class
  def predict(self, X):
    return np.argmax(self.predict_log_proba(X), axis=1) # Simply picking the column which has highest value for each word of the given array as test set


In [ ]:
#m<n
A = 
B =
print(np.linalg.inv(np.dot(A,A.transpose())))
X = np.dot(np.dot(A.transpose(),np.linalg.inv(np.dot(A,A.transpose()))),B)
print(X)